name: qa
on:
  push:
    branches: [staging]
jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      vm: vm-qa
      branch: staging
      port: "3002"
      environment: qa

