name: Reusable Deploy
on:
  workflow_call:
    inputs:
      vm: {type: string, required: true}
      branch: {type: string, required: true}
      port: {type: string, required: true}
      environment: {type: string, required: true}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - uses: google-github-actions/setup-gcloud@v2
    - name: Deploy
      run: |
        gcloud compute ssh ${{ inputs.vm }} --zone=us-central1-a --command="
        mkdir -p ~/backups;
        cp -r ~/student-management ~/backups/student-management-$(date +%s) || true;
        cd ~/student-management;
        git fetch origin;
        git checkout ${{ inputs.branch }};
        git reset --hard origin/${{ inputs.branch }};
        cat > .env <<EOF
        MONGO_URI=${{ secrets.PROD_MONGO_URI }}
        PORT=${{ inputs.port }}
        NODE_ENV=${{ inputs.environment }}
        EOF
        npm ci;
        pm2 delete student-app-${{ inputs.environment }} || true;
        pm2 start server.js --name student-app-${{ inputs.environment }};
        pm2 save;
        sudo systemctl reload nginx;"

